# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 12:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0019_auto_20170104_1736'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeber', models.CharField(max_length=10)),
                ('countResidents', models.IntegerField(null=True)),
                ('countRooms', models.IntegerField(default=0)),
                ('area', models.IntegerField(default=0)),
                ('HotArea', models.IntegerField(default=0)),
                ('isRent', models.BooleanField(default=False, verbose_name='В аренде')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Podezd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numder', models.CharField(max_length=10)),
                ('note', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subsidyi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('percent', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='podezd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Podezd'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartments.Level'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.UserProfile'),
        ),
    ]
