# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='subsidyi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apartments.subsidyi'),
        ),
    ]
