# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_auto_20170212_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='countResidents',
            field=models.IntegerField(default=0),
        ),
    ]
