# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_auto_20170302_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
