# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0004_auto_20170212_1222'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patterns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit_measure', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='subsidy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Tariffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit_measure', models.CharField(blank=True, max_length=15)),
                ('enable', models.BooleanField(default=True)),
                ('price0_t1', models.FloatField(blank=True, default=0, max_length=20)),
                ('price0_t2', models.FloatField(blank=True, default=0, max_length=20)),
                ('benefit0_t1', models.IntegerField(blank=True, default=0)),
                ('benefit0_t2', models.IntegerField(blank=True, default=0)),
                ('level1_t1', models.FloatField(blank=True, default=0, max_length=15)),
                ('level1_t2', models.FloatField(blank=True, default=0, max_length=15)),
                ('price1_t1', models.FloatField(blank=True, default=0, max_length=20)),
                ('price1_t2', models.FloatField(blank=True, default=0, max_length=20)),
                ('benefit1_t1', models.IntegerField(blank=True, default=0)),
                ('benefit1_t2', models.IntegerField(blank=True, default=0)),
                ('level2_t1', models.FloatField(blank=True, default=0, max_length=15)),
                ('level2_t2', models.FloatField(blank=True, default=0, max_length=15)),
                ('price2_t1', models.FloatField(blank=True, default=0, max_length=20)),
                ('price2_t2', models.FloatField(blank=True, default=0, max_length=20)),
                ('benefit2_t1', models.IntegerField(blank=True, default=0)),
                ('benefit2_t2', models.IntegerField(blank=True, default=0)),
                ('coment', models.TextField(blank=True, default='', max_length=100)),
                ('residents', models.ManyToManyField(to='apartments.Apartment')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariff.Tariff_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_readings', models.FloatField(blank=True, default=0, max_length=15)),
                ('current_raadings', models.FloatField(blank=True, default=0, max_length=15)),
                ('previous_readings_c2', models.FloatField(blank=True, default=0, max_length=15)),
                ('current_raadings_c2', models.FloatField(blank=True, default=0, max_length=15)),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('dateAdd', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=15)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Apartment')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariff.Tariffs')),
            ],
        ),
        migrations.AddField(
            model_name='patterns',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariff.Tariff_type'),
        ),
    ]
