# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffs',
            name='benefit0_t1',
            field=models.BooleanField(default=False, verbose_name='Льгота'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='benefit0_t2',
            field=models.BooleanField(default=False, verbose_name='Льгота'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='benefit1_t1',
            field=models.BooleanField(default=False, verbose_name='Льгота'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='benefit1_t2',
            field=models.BooleanField(default=False, verbose_name='Льгота'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='benefit2_t1',
            field=models.BooleanField(default=False, verbose_name='Льгота'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='benefit2_t2',
            field=models.BooleanField(default=False, verbose_name='Льгота'),
        ),
    ]
