# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffs',
            name='datEnd',
            field=models.DateField(blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariffs',
            name='datStart',
            field=models.DateField(blank=True),
            preserve_default=False,
        ),
    ]
