# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='FirstName',
            field=models.CharField(default=2016, max_length=30, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='LastName',
            field=models.CharField(default=2016, max_length=30, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='OSBBname',
            field=models.CharField(default=2016, max_length=50, verbose_name='Название OSBB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='addres',
            field=models.CharField(default=2016, max_length=50, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='homenumber',
            field=models.CharField(default=2016, max_length=10, verbose_name='Номер дома'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number',
            field=models.CharField(default=2016, max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='patronymic',
            field=models.CharField(default=2016, max_length=30, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street',
            field=models.CharField(default=2016, max_length=50, verbose_name='Улица'),
            preserve_default=False,
        ),
    ]
