# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_auto_20161212_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='podezd',
        ),
        migrations.RemoveField(
            model_name='podezd',
            name='user',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Podezd',
        ),
    ]
