# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_auto_20161212_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='number',
            field=models.CharField(default=2016, max_length=10),
            preserve_default=False,
        ),
    ]
