# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0012_auto_20161222_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
