# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0013_auto_20161222_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pc',
            field=models.CharField(default=2017, max_length=30, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
