# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0015_remove_userprofile_pc'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSBBProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OSBBname', models.CharField(max_length=50, verbose_name='Название OSBB')),
                ('addres', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('homenumber', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'Профили',
                'verbose_name': 'Профиль',
            },
        ),
    ]
