# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0016_osbbprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osbbprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='OSBBname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название OSBB'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='addres',
            field=models.CharField(blank=True, max_length=50, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='homenumber',
            field=models.CharField(blank=True, max_length=10, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street',
            field=models.CharField(blank=True, max_length=50, verbose_name='Улица'),
        ),
        migrations.DeleteModel(
            name='OSBBProfile',
        ),
    ]
