# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0017_auto_20170104_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isOSMD',
            field=models.BooleanField(default=False),
        ),
    ]
