# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0018_auto_20170104_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='isOSMD',
            field=models.BooleanField(default=False, verbose_name='Является ОСМД'),
        ),
    ]
